"""Configuration for the professional BTCUSDT signal system."""

import os
from dotenv import load_dotenv

load_dotenv()

# --- Market ---
SYMBOL = "BTCUSDT"
INTERVAL = "15m"
CANDLE_LIMIT = 200

# --- Indicators ---
EMA_FAST = 20
EMA_SLOW = 50
RSI_PERIOD = 14
ATR_PERIOD = 14
VOLUME_LOOKBACK = 20

RSI_BULL_MIN = 50
RSI_BULL_MAX = 68
RSI_BEAR_MIN = 32
RSI_BEAR_MAX = 50
RSI_OVERSOLD = 30
RSI_OVERBOUGHT = 70
RSI_EXTREME_OVERSOLD = 25
RSI_EXTREME_OVERBOUGHT = 75

VOLUME_SPIKE_MULTIPLIER = 1.5
TREND_STRENGTH_MIN = 0.08  # % distance EMA20 vs EMA50

# --- Swings / S&R ---
SWING_LOOKBACK = 20
BREAKOUT_PIERCE_PCT = 0.001
FAKE_BREAKOUT_WICK_RATIO = 0.6
SUPPORT_RESISTANCE_BUFFER = 0.0015

# --- Candle patterns ---
DOJI_BODY_RATIO = 0.1
HAMMER_WICK_RATIO = 0.55
HAMMER_MAX_BODY_RATIO = 0.35
HAMMER_OPPOSITE_WICK_MAX = 0.15
STRONG_BODY_RATIO = 0.55
REJECTION_WICK_RATIO = 0.5
LIQUIDITY_SWEEP_PIERCE_PCT = 0.0015
LIQUIDITY_SWEEP_WICK_RATIO = 0.45
MIN_CANDLE_SCORE_CONFIRM = 15
PATTERN_SCORE_ENGULFING = 25
PATTERN_SCORE_HAMMER = 20
PATTERN_SCORE_REJECTION = 22
PATTERN_SCORE_LIQUIDITY = 28
PATTERN_SCORE_BREAKOUT = 24
PATTERN_SCORE_FAKE_TRAP = 18
PATTERN_SCORE_MAX = 50

# --- Risk / levels ---
ATR_SL_MULTIPLIER = 1.5
ATR_TP_MULTIPLIER = 3.0
MIN_RISK_REWARD = 2.0
SWING_SL_BUFFER = 0.0012
MAX_SL_PCT = 2.5
MIN_SL_PCT = 0.35

# --- Late entry / structure ---
PANIC_DUMP_PCT = 2.8
PANIC_DUMP_BARS = 8
LATE_ENTRY_RSI_OVERSOLD = 28
LATE_ENTRY_RSI_OVERBOUGHT = 72
RETEST_EMA_TOLERANCE = 0.004

# --- Signal thresholds ---
CONFIDENCE_STRONG = 82
CONFIDENCE_TRADE = 62
NEWS_CONFLICT_PENALTY = 18

# --- Scoring weights (sum 100) ---
WEIGHT_EMA = 14
WEIGHT_RSI = 12
WEIGHT_VOLUME = 10
WEIGHT_TREND = 10
WEIGHT_STRUCTURE = 14
WEIGHT_CANDLE = 18
WEIGHT_NO_FAKE = 12
WEIGHT_NEWS = 10

# --- News ---
NEWS_CACHE_SECONDS = 300
CRYPTOCOMPARE_NEWS_URL = "https://min-api.cryptocompare.com/data/v2/news/"
FEAR_GREED_URL = "https://api.alternative.me/fng/?limit=1"
CRYPTOPANIC_URL = "https://cryptopanic.com/api/v1/posts/"
CRYPTOPANIC_TOKEN = os.getenv("CRYPTOPANIC_TOKEN", "")

# --- Backtest / paper ---
PAPER_TRADING = os.getenv("PAPER_TRADING", "true").lower() == "true"
SIGNAL_HISTORY_FILE = os.getenv("SIGNAL_HISTORY_FILE", "data/signal_history.json")
SIGNAL_HISTORY_MAX = 20
EVALUATION_BARS = 8

# --- Runtime ---
SCAN_INTERVAL_SECONDS = int(os.getenv("SCAN_INTERVAL_SECONDS", "60"))
BINANCE_BASE_URL = os.getenv("BINANCE_BASE_URL", "https://api.binance.com")
HOST = os.getenv("HOST", "0.0.0.0")
PORT = int(os.getenv("PORT", "8080"))
BINANCE_API_KEY = os.getenv("BINANCE_API_KEY", "")
BINANCE_API_SECRET = os.getenv("BINANCE_API_SECRET", "")
